server:
   port: 8002
   
spring:
   application:
      name: bindex
   datasource:
      url: jdbc:mysql://127.0.0.1/s3-bench?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
   
   servlet:
      multipart:
         max-request-size:  10MB
         max-file-size:  10MB
      
   mail:
      host:  smtp.qq.com
      username:  1529072552@qq.com
      password:  xsuwaxihxxuqijea
      default-encoding:  UTF-8 

   redis:
      database:  0
      host:  127.0.0.1
      port:  6379
      password:       
             
      
mail:
   fromMail: 
      addr:  1529072552@qq.com
  
logging:
   level:
      com:
         bench:
            Bench: debug
              # dao: debug
            # web: warn
